version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333
    networks:
      - maowrag-network-backend
  
  qdrant:
    image: "qdrant/qdrant:v1.12.0"
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__ON_DISK_PAYLOAD: 'true'
    networks:
      - maowrag-network-backend
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/6333 && echo -e 'GET /healthz HTTP/1.1\r\nHost: localhost\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 180s
      retries: 3
      start_period: 40s
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DB=maowrag
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    networks:
      - maowrag-network-backend
    command: --default-authentication-plugin=mysql_native_password

networks:
  maowrag-network-backend:
    driver: bridge